version: "3.8"

services:
  pilotott:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: pilotott
    volumes:
      - ../systools:/app/systools
    restart: unless-stopped
